### ISSUE TITLE
File help

### ISSUE THREAD

**Issue by RapidBeanz** [Ierofantis/Chrome_Venom#1]
Hello,

I am somewhat new to python so I am unsure of what I am supposed to do to make this program run and stuff. I got it to the editing screen but what text do I have to change. I would really appreciate of you could list the steps for me.
hunterclark890@gmail.com
Thanks
Parker

**Comment by Ierofantis** [comment]
Hi,

Can you tell me how and if you try to run this program or if you had a specific error?

**Comment by RapidBeanz** [comment]
Well basically I haven't tried to run this yet but I know that I am suppose to edit of some of the green text in the program right? I am just wondering what do I have to change to make it send it to my email and work and stuff.

**Comment by RapidBeanz** [comment]
Hello, 

I am still confused on what text we are supposed to edit out can you please help me.
