### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by fahimanwer** [Ierofantis/Chrome_Venom#4]
Hey, First of all thanks for creating a great thing. But, I am full noob in coding. Can you please create a video tutorial. Please sir.

**Comment by mrn1992** [comment]
hey
me either

**Comment by AmmarHaddadi** [comment]
> Hey, First of all thanks for creating a great thing. But, I am full noob in coding. Can you please create a video tutorial. Please sir.

hi , you will need a Python IDE first , like PyCharm , Visual Studio Code ...
just make sure you download it from the official website
next , open the ide , click on file > open file then open the Chrome_Venom script 
read the script , and add your email & password in the specified place
